// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk1MYsh5ypjQD8q1Mb33Zvshqj4XBuOwU',
    appId: '1:490953342675:web:b09527696e157c4ce35e26',
    messagingSenderId: '490953342675',
    projectId: 'udev1-e6949',
    authDomain: 'udev1-e6949.firebaseapp.com',
    storageBucket: 'udev1-e6949.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOhESS8p5vnOpW0cqZu4vHT239m1e1OqI',
    appId: '1:490953342675:android:ad4a18007c088fe8e35e26',
    messagingSenderId: '490953342675',
    projectId: 'udev1-e6949',
    storageBucket: 'udev1-e6949.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD960kkCQVFWW2OtGmXkkOYuwWH1BKiQU0',
    appId: '1:490953342675:ios:01680637ffca82a1e35e26',
    messagingSenderId: '490953342675',
    projectId: 'udev1-e6949',
    storageBucket: 'udev1-e6949.appspot.com',
    iosBundleId: 'com.mycompany.duev1',
  );
}
